apiVersion: v2
name: yet-another-cloudwatch-exporter
description: Yet Another Cloudwatch Exporter
type: application
version: 0.38.0
appVersion: "v0.38.0-alpha"
home: https://github.com/vkobets/yet-another-cloudwatch-exporter
sources:
- https://github.com/vkobets/yet-another-cloudwatch-exporter
keywords:
- aws
- cloudwatch
- prometheus
- exporter
- yet-another
- yace
